### ISSUE TITLE
Stack trace when using -B

### ISSUE THREAD

**Issue by kergoth** [sjl/friendly-find#12]
```
$ ~/Sandbox/friendly-find/ffind -B
Traceback (most recent call last):
  File "/home/clarson/Sandbox/friendly-find/ffind", line 843, in <module>
    main()
  File "/home/clarson/Sandbox/friendly-find/ffind", line 834, in main
    search(query)
  File "/home/clarson/Sandbox/friendly-find/ffind", line 485, in search
    _search(query, '.', 0, get_initial_ignorers())
  File "/home/clarson/Sandbox/friendly-find/ffind", line 471, in _search
    if match(query, path, item):
  File "/home/clarson/Sandbox/friendly-find/ffind", line 458, in match
    result = _match()
  File "/home/clarson/Sandbox/friendly-find/ffind", line 451, in _match
    with os.fdopen(fd) as f:
IOError: [Errno 21] Is a directory: '<fdopen>'
```

**Comment by arpit1997** [comment]
> $ ~/Sandbox/friendly-find/ffind -B
Traceback (most recent call last):
  File "/home/clarson/Sandbox/friendly-find/ffind", line 843, in <module>
    main()
  File "/home/clarson/Sandbox/friendly-find/ffind", line 834, in main
    search(query)
  File "/home/clarson/Sandbox/friendly-find/ffind", line 485, in search
    _search(query, '.', 0, get_initial_ignorers())
  File "/home/clarson/Sandbox/friendly-find/ffind", line 471, in _search
    if match(query, path, item):
  File "/home/clarson/Sandbox/friendly-find/ffind", line 458, in match
    result = _match()
  File "/home/clarson/Sandbox/friendly-find/ffind", line 451, in _match
    with os.fdopen(fd) as f:
IOError: [Errno 21] Is a directory: '<fdopen>'
The reason for this error is that you are trying to open a directory which does not exist or you don't have access to this directory.
:smile_cat: :smile_cat:

**Comment by kergoth** [comment]
No, the reason for the error is that ffind blindly opens the path without checking that it's actually a file first. It has nothing to do with anything the user does. It errors when run from any path that includes a sub-directory.

**Comment by arpit1997** [comment]
@kergoth  Ok Cool I got your point. So should i say that it is just a handed exception or unhandled case .

> File "/home/clarson/Sandbox/friendly-find/ffind", line 451, in _match
with os.fdopen(fd) as f:
IOError: [Errno 21] Is a directory: ''

This kind of error i only had seen when we are opening a directory using file open command so i commented it sorry if i have given some wring suggestion
:smile_cat: :no_smoking:
