### ISSUE TITLE
Broken pipe traceback

### ISSUE THREAD

**Issue by dwijnand** [sjl/friendly-find#18]
I recently messed up and typed `ffind | my.file.txt` instead of `ffind | grep my.file.txt` (lazy mode searching), and got this traceback:

    Traceback (most recent call last):
      File "/usr/local/bin/ffind", line 856, in <module>
        main()
      File "/usr/local/bin/ffind", line 847, in main
        search(query)
      File "/usr/local/bin/ffind", line 485, in search
        _search(query, '.', 0, get_initial_ignorers())
      File "/usr/local/bin/ffind", line 482, in _search
        _search(query, d, depth + 1, ignorers)
      File "/usr/local/bin/ffind", line 482, in _search
        _search(query, d, depth + 1, ignorers)
      File "/usr/local/bin/ffind", line 482, in _search
        _search(query, d, depth + 1, ignorers)
      File "/usr/local/bin/ffind", line 482, in _search
        _search(query, d, depth + 1, ignorers)
      File "/usr/local/bin/ffind", line 482, in _search
        _search(query, d, depth + 1, ignorers)
      File "/usr/local/bin/ffind", line 482, in _search
        _search(query, d, depth + 1, ignorers)
      File "/usr/local/bin/ffind", line 482, in _search
        _search(query, d, depth + 1, ignorers)
      File "/usr/local/bin/ffind", line 482, in _search
        _search(query, d, depth + 1, ignorers)
      File "/usr/local/bin/ffind", line 482, in _search
        _search(query, d, depth + 1, ignorers)
      File "/usr/local/bin/ffind", line 482, in _search
        _search(query, d, depth + 1, ignorers)
      File "/usr/local/bin/ffind", line 482, in _search
        _search(query, d, depth + 1, ignorers)
      File "/usr/local/bin/ffind", line 472, in _search
        out(path, '\0' if options.zero else '\n')
      File "/usr/local/bin/ffind", line 109, in out
        sys.stdout.write(s + line_ending)
    IOError: [Errno 32] Broken pipe

For some reason while trying to reproduce (I moved to another directory and did the same command) I got this instead :-/

    close failed in file object destructor:
    sys.excepthook is missing
    lost sys.stderr

**Comment by jpouellet** [comment]
Yeah, this is just a unix thing. When grep (or any program) exits, it closes all its file descriptors (including the pipe between it and ffind). Then, when ffind (or any program) tries to write to the write end of the now-closed pipe with nothing on the other end, it will get a SIGPIPE signal. The default behavior upon receiving a SIGPIPE is [http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/signal.h.html](to just die), so you never notice it for most programs, but in this case python catches it and gives you a backtrace.

The correct behavior in this case is to just die silently.
